version: "3.2"
services:
  postgres_keycloak_demo:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: patient
    volumes:
      - keycloak_demo_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - demo_network

volumes:
  demo_data:

networks:
  demo_network:
    driver: bridge